#!/usr/bin/env ruby

require 'colorize'
require 'net/http'
require 'tty-progressbar'
require 'nhentai-api'

DONE      = 'DONE'.colorize(:green)
ERROR     = 'ERROR'.colorize(:red)
FINISHED  = 'DOWNLOAD FINISHED'.colorize(:blue)

def print_help
  exemple = '191049'.colorize(:green)

  puts  "Usage: urbanity [ID]\n\n" \
        "Exemple:\n" \
        "https://nhentai.net/g/#{exemple}\n" \
        "$> urbanity #{exemple}\n"
  exit
end

def create_folder
  Dir.mkdir(ARGV[0])
  puts "[#{DONE}] folder #{ARGV[0]} created"
end

def initiate(doujinshi)
  bar = TTY::ProgressBar.new('downloading [:bar] :current / :total | ETA: :eta',
                            total: doujinshi.count_pages, width: 50, head: '>')

  create_folder
  doujinshi.pages.each_with_index { |page, index| download(page, index + 1, bar) }
  put_message("[#{FINISHED}]")
end

def download(page, index, bar)
  client    = Net::HTTP.get_response(URI(page))
  extention = page.slice(page.length - 3..page.length)

  File.open("#{ARGV[0]}/#{index}.#{extention}", 'wb') { |file| file.puts client.body }
  bar.advance(1)
end

def put_message(message)
  puts message
  exit
end

print_help if ARGV.empty?
doujinshi = Doujinshi.new(ARGV[0])
put_message("[#{ERROR}] This doujinshi does not exist") if doujinshi.exists?
File.exist?(ARGV[0]) ? put_message("[#{ERROR}] Folder already exist") : initiate(doujinshi)
